Rahul/android prompt
Hack-PSU/frontend-app pull request #46
Opened 2020-10-18 19:37 UTC by rsquared226

Android doesn't have its own native prompt so we had to make our own.
This prompt relies on the state under `PromptModal.tsx`, which contains the data for what is shown on the dialog and if it's visible or not.

This works on Android fine, does it break on iOS at all? Also, the prompt bug after signing in on iOS does not happen on Android.

![Screenshot_20201018-151912](https://user-images.githubusercontent.com/7365763/96377779-d6e29d00-1155-11eb-9461-8200ea249ec7.jpg)

2020-10-19 19:58 UTC, jaytran505 approved these changes

2020-10-21 23:33 UTC, mbullington requested changes
Looks good to me minus simple change. Thanks for working on it!!

2020-10-21 23:33 UTC, mbullington commented on src/components/AndroidPrompt.tsx
> +    }
Can we use useCallback hook here? I feel this would improve performance

2020-10-22 19:43 UTC, helloimali approved these changes

2020-10-22 23:16 UTC, rsquared226 commented
@mbullington just did, did I do it right?

2020-10-23 19:54 UTC, mbullington approved these changes

2020-10-23 19:54 UTC, merged